/**
 * Workday DOM MutationObserver
 * Tracks dynamic form updates, lazy-loaded sections, and modal appearances
 */

export class WorkdayObserver {
  constructor(onDomChangedCallback, debounceMs = 400) {
    this.callback = onDomChangedCallback;
    this.debounceMs = debounceMs;
    this.timeoutId = null;
    this.observer = null;
    this.isObserving = false;
  }

  start(targetNode = document.body) {
    if (this.isObserving || !targetNode) return;

    this.observer = new MutationObserver((mutations) => {
      // Filter out mutations generated by our own assistant widget or green highlights
      const isExternalChange = mutations.some(m => {
        const target = m.target;
        if (!target) return false;
        if (target.id === 'workday-ai-assistant-root' || target.closest?.('#workday-ai-assistant-root')) {
          return false;
        }
        return true;
      });

      if (isExternalChange) {
        this.debounceTrigger();
      }
    });

    this.observer.observe(targetNode, {
      childList: true,
      subtree: true,
      attributes: false
    });

    this.isObserving = true;
  }

  debounceTrigger() {
    if (this.timeoutId) {
      clearTimeout(this.timeoutId);
    }
    this.timeoutId = setTimeout(() => {
      if (this.callback) {
        this.callback();
      }
    }, this.debounceMs);
  }

  stop() {
    if (this.observer) {
      this.observer.disconnect();
      this.observer = null;
    }
    if (this.timeoutId) {
      clearTimeout(this.timeoutId);
      this.timeoutId = null;
    }
    this.isObserving = false;
  }
}
